name: snaptest
version: git
summary: Testing snapcraft build.
description: Testing snapcraft build.
confinement: strict
base: core18
parts:
  snaptest:
    plugin: go
    go-channel: 1.13/stable
    source: .
    source-type: git

apps:
  snaptest:
    command: bin/snaptest
